### ISSUE TITLE
/spec/support/feature_helper.rb keeps flickering

### ISSUE THREAD

**Issue by jpalmieri** [jpalmieri/breautodo#42]
```
1) User updates list successfully
     Failure/Error: sign_in(user)
       expected to find text "Signed in successfully." in "Invalid email or password. Breautodo About Lists All Todos Sign In Sign in Remember me Sign up Forgot your password? Resend confirmation email"
     # ./spec/support/feature_helper.rb:15:in `sign_in'
     # ./spec/features/user_updates_list_spec.rb:10:in `block (2 levels) in <top (required)>'
```

**Comment by jpalmieri** [comment]
hasn't happened in a long time. Closing for now.

**Comment by jpalmieri** [comment]
this started happening again in a branch, and it seems to be related to an incorrectly database cleaner:
https://github.com/DatabaseCleaner/database_cleaner#rspec-with-capybara-example
